apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maskwise.fullname" . }}-secret
  labels:
    {{- include "maskwise.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "maskwise.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ printf "redis://:%s@%s-redis-master:6379" .Values.redis.auth.password (include "maskwise.fullname" .) | b64enc | quote }}
  {{- end }}
  jwt-secret: {{ .Values.api.env.JWT_SECRET | default (randAlphaNum 32) | b64enc | quote }}